// Mirrors server/src/middleware/permissions.js — role × feature matrix.
// ✅ = full access. Use `can(role, feature)` for UI gating; backend requireRole is authoritative.
import { ROLES } from './roles';

export const FEATURES = {
  DASHBOARD: 'DASHBOARD',
  USER_MANAGE: 'USER_MANAGE',
  ORG_MANAGE: 'ORG_MANAGE',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',
  EVENT_CREATE: 'EVENT_CREATE',
  VENUE_MANAGE: 'VENUE_MANAGE',
  SESSION_MANAGE: 'SESSION_MANAGE',
  SPEAKER_MANAGE: 'SPEAKER_MANAGE',
  SPONSOR_MANAGE: 'SPONSOR_MANAGE',
  TICKET_MANAGE: 'TICKET_MANAGE',
  REGISTRATION_MANAGE: 'REGISTRATION_MANAGE',
  CHECKIN_PERFORM: 'CHECKIN_PERFORM',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  STAFF_MANAGE: 'STAFF_MANAGE',
  ANNOUNCE_SEND: 'ANNOUNCE_SEND',
  AI_CONTENT: 'AI_CONTENT',
  AI_RECOMMEND: 'AI_RECOMMEND',
  ANALYTICS: 'ANALYTICS',
  FEEDBACK_VIEW: 'FEEDBACK_VIEW',
  DELIVERABLE_MANAGE: 'DELIVERABLE_MANAGE',
  BRAND_MANAGE: 'BRAND_MANAGE',
  // Own-scope features
  SPEAKER_HUB: 'SPEAKER_HUB',
  SPONSOR_PORTAL: 'SPONSOR_PORTAL',
  STAFF_OPS: 'STAFF_OPS',
  MY_TICKETS: 'MY_TICKETS',
};

const {
  PLATFORM_ADMIN: ADMIN,
  EVENT_ORGANIZER: ORG,
  EVENT_STAFF: STAFF,
  SPEAKER,
  ATTENDEE,
  SPONSOR,
} = ROLES;

// Full-access allow lists (own-scope handled separately below)
const MATRIX = {
  [FEATURES.DASHBOARD]: [ADMIN, ORG, STAFF, SPEAKER, ATTENDEE, SPONSOR],
  [FEATURES.USER_MANAGE]: [ADMIN],
  [FEATURES.ORG_MANAGE]: [ADMIN],
  [FEATURES.SUBSCRIPTION_MANAGE]: [ADMIN, ORG],
  [FEATURES.EVENT_CREATE]: [ORG],
  [FEATURES.VENUE_MANAGE]: [ORG, STAFF],
  [FEATURES.SESSION_MANAGE]: [ORG],
  [FEATURES.SPEAKER_MANAGE]: [ORG],
  [FEATURES.SPONSOR_MANAGE]: [ORG],
  [FEATURES.TICKET_MANAGE]: [ORG],
  [FEATURES.REGISTRATION_MANAGE]: [ORG],
  [FEATURES.CHECKIN_PERFORM]: [STAFF],
  [FEATURES.ATTENDANCE_MARK]: [STAFF],
  [FEATURES.STAFF_MANAGE]: [ORG],
  [FEATURES.ANNOUNCE_SEND]: [ORG],
  [FEATURES.AI_CONTENT]: [ORG],
  [FEATURES.AI_RECOMMEND]: [ATTENDEE],
  [FEATURES.ANALYTICS]: [ADMIN, ORG],
  [FEATURES.FEEDBACK_VIEW]: [ORG, SPEAKER],
  [FEATURES.DELIVERABLE_MANAGE]: [ORG],
  [FEATURES.BRAND_MANAGE]: [ORG],
  // Hubs: organizer manages, owners see own scope (matrix: Admin — here)
  [FEATURES.SPEAKER_HUB]: [ORG, SPEAKER],
  [FEATURES.SPONSOR_PORTAL]: [ORG, SPONSOR],
  [FEATURES.STAFF_OPS]: [STAFF],
  [FEATURES.MY_TICKETS]: [ATTENDEE],
};

export const can = (role, feature) => (MATRIX[feature] || []).includes(role);

export const isAdmin = (role) => role === ADMIN;
export const isOrganizer = (role) => role === ORG;
